config/routes.rb
require "sidekiq/web"
Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == ENV["HTTP_USERNAME"] && password == ENV["HTTP_PASSWORD"]
end

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  post "/graphql", to: "graphql#execute"
  resources :episodes, only: [:index] do
    member do
      get "download"
    end
  end

  resources :movie_downloads, only: [:index] do
    member do
      get "download"
    end
  end

  resources :ptp_movie_recommendations, only: [:index]

  mount Sidekiq::Web => "/sidekiq"

  root to: "home#index"
end

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: home_index_path} Broad
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Download Movie', new_movie_path

    / /.nav-collapse

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testo2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <%= vite_stylesheet_tag 'typography', media: 'print' %>
  </head>
</head>
<body>
  Hej
</body>
</html>